name: patch-release

on:
  create:
    tags:
      - "v0.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dmenu 5.2
        run: git clone -b 5.2 --depth=1 https://git.suckless.org/dmenu a
      - name: Checkout dmenu_fzy
        uses: actions/checkout@v3
        with:
          path: b
      - name: Clear files exclusive to dmenu_fzy
        run: rm -rf a/.git b/.git b/.gitignore b/.github
      - name: Create patch file
        continue-on-error: true
        run: diff -rupN a b > dmenu-fzy-${{ github.ref_name }}-5.2.diff
      - name: Release file
        uses: softprops/action-gh-release@v1
        with:
          files: dmenu-fzy-${{ github.ref_name }}-5.2.diff
